remote_theme             : "mmistakes/minimal-mistakes@4.27.1"

minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "en-US"
title                    : "Bagrat Mukaelyan | Software Engineer | Writer"
title_separator          : "-"
subtitle                 : "Yet another developer's blog."
name                     : &name "Bagrat Mukaelyan"
description              : &description "“Adapt what is useful, reject what is useless, and add what is specifically your own.” - *Bruce Lee*"
url                      : https://mbagrat.com
baseurl                  : ""
repository               : "mbagrat/personal-website"
teaser                   : "/assets/images/500x300.png"
logo                     : "/assets/images/site-logo.png"
masthead_title           : "MBagrat"
breadcrumbs              : false


comments:
  provider               : "staticman_v2"
  staticman:
    branch               : "main"
    endpoint             : "https://staticman-comment-app.herokuapp.com/v3/entry/github/"
reCaptcha:
  enabled                : true
  siteKey                : 6LdpH4oeAAAAAOSgpxH1ORz0Tx9MLFHc3BUwRBVi
  secret                 : MwBYuBHgbH6dBExT1iJwBRX3sUyaCRHwzCZh+vpWxYdxba5OfLCCpcGctPMZPiMQ44ByLlK+u1og5sNMYf+rOrD9NFkgVJD34tHiTHeN1ly9z0AJUXqAmWThtN7LczogMO3xM3fX8B+2RfQN0rJsN3XB37FDk+/aFPQZffZTlK0=


atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true

search                   : true
search_full_content      : true
search_provider          : lunr


# SEO Related
google_site_verification : "AJPLan1uJ8g5rfs7XE1u68DTbIkNMLdgF_Rc68f8HxU"
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "bagratmukaelyan"
facebook:
  username               : &facebook "mbagrat"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png"
social:
  type                   : Person
  name                   : *name
  links:
    - "https://www.twitter.com/bagratmukaelyan"
    - "https://www.facebook.com/mbagrat"
    - "https://www.linkedin.com/in/bagratmukaelyan"
    - "https://www.t.me/mbagrat"
    - "https://www.instagram.com/bagratmukaelyan/"

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "GTM-592SNKV"
    anonymize_ip         : true


# Site Author
author:
  name                   : *name
  avatar                 : "/assets/images/bagrat-mukaelyan.jpeg"
  bio                    : *description
  location               : "Yerevan, Armenia"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bagrat.mukaelyan@gmail.com"
    - label: "Resume"
      icon: "fas fa-fw fa-file-pdf"
      url: "https://mbagrat.com/resume"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.mbagrat.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://www.twitter.com/bagratmukaelyan"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bagratmukaelyan"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/mbagrat"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://www.t.me/mbagrat"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MBagrat"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/MBagrat"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/MBagrat/"
    - label: "Terms"
      icon: "fas fa-fw fa-file-alt"
      url: "/terms"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .fleet
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      show_date: true
      author_profile: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: /:categories/:title/
timezone: Asia/Yerevan


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

after_footer_analytics_scripts:
  - /assets/js/cookie-consent.js
